version: "3.8"

networks:
  intranet_bridge:
    driver: bridge
    
services:

  # POSTGRES (simulando RDS local)
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - intranet_bridge

  # PGADMIN (client web para Postgres)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: lemes_vilarinho@yahoo.com.br
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    networks:
      - intranet_bridge

  # LOCALSTACK (S3, DynamoDB, Lambda, EC2, VPC)
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # Serviços internos
    environment:
      - SERVICES=s3,dynamodb,lambda,ec2,vpc
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - LOCALSTACK_HOST=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - intranet_bridge

  # localstack:
  #   image: localstack/localstack:latest
  #   container_name: localstack
  #   ports:
  #   - "4566:4566" # Porta principal
  #   - "4510-4559:4510-4559" # portas para serviços antigos (opcional)
  #   environment:
  #   - SERVICES=s3,sts,iam,lambda,dynamodb
  #   - DEBUG=1
  #   - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #   - "./volume:/var/lib/localstack"
  #   - "/var/run/docker.sock:/var/run/docker.sock"

  # PYTHON CLIENT (para testes com boto3 e AWS CLI)
  python-client:
    container_name: python-client
    image: python:3.10-slim
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - ./scripts:/scripts
    networks:
      - intranet_bridge
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    

volumes:
  postgres_db:


